from typing import Literal

from pydantic import BaseModel


AlgorithmCategory = Literal[
    "sorting",
    "searching",
    "graph",
    "dynamic_programming",
    "backtracking",
    "trees",
]


class TimeComplexity(BaseModel):
    best: str
    average: str
    worst: str


class AlgorithmMetadata(BaseModel):
    id: str
    label: str
    name: str
    category: AlgorithmCategory
    description: str
    time_complexity: TimeComplexity
    space_complexity: str
    notes: list[str]
    pseudocode: list[str]


class AlgorithmsResponse(BaseModel):
    sorting: list[AlgorithmMetadata]
    searching: list[AlgorithmMetadata]
    graph: list[AlgorithmMetadata]
    dynamic_programming: list[AlgorithmMetadata]
    backtracking: list[AlgorithmMetadata]
    trees: list[AlgorithmMetadata]


def metadata(
    algorithm_id: str,
    name: str,
    category: AlgorithmCategory,
    description: str,
    best: str,
    average: str,
    worst: str,
    space: str,
    *notes: str,
) -> AlgorithmMetadata:
    return AlgorithmMetadata(
        id=algorithm_id,
        label=name,
        name=name,
        category=category,
        description=description,
        time_complexity=TimeComplexity(
            best=best,
            average=average,
            worst=worst,
        ),
        space_complexity=space,
        notes=list(notes),
        pseudocode=ALGORITHM_PSEUDOCODE[algorithm_id],
    )


ALGORITHM_PSEUDOCODE = {
    "bubble_sort": [
        "for each pass through the unsorted values",
        "  compare each adjacent pair",
        "  if the left value is larger, swap the pair",
        "  stop early if the pass made no swaps",
        "return the sorted array",
    ],
    "selection_sort": [
        "for each position in the array",
        "  assume this position holds the minimum",
        "  compare the minimum with each remaining value",
        "  remember any smaller value",
        "  swap the minimum into the current position",
        "return the sorted array",
    ],
    "insertion_sort": [
        "for each value after the first",
        "  compare it with values in the sorted prefix",
        "  shift larger values one position right",
        "  insert the value into the open position",
        "return the sorted array",
    ],
    "merge_sort": [
        "split the current range into two halves",
        "recursively sort the left and right halves",
        "compare the next value from each half",
        "write the smaller values back in order",
        "mark the range as merged",
        "return the sorted array",
    ],
    "quick_sort": [
        "choose the final value as the pivot",
        "compare each value with the pivot",
        "swap smaller values into the left partition",
        "move the pivot between the partitions",
        "recursively sort both partitions",
        "return the sorted array",
    ],
    "heap_sort": [
        "build a max heap from the array",
        "compare a root with its children",
        "swap the root with its largest child when needed",
        "move the heap maximum to the array's end",
        "restore the reduced heap",
        "return the sorted array",
    ],
    "shell_sort": [
        "start with a gap equal to half the array length",
        "compare values separated by the gap",
        "shift larger values forward by the gap",
        "insert the value into its gapped position",
        "halve the gap and repeat",
        "return the sorted array",
    ],
    "cocktail_shaker_sort": [
        "scan left to right through the active range",
        "  compare adjacent values and swap when needed",
        "shrink the right boundary",
        "scan right to left through the active range",
        "  compare adjacent values and swap when needed",
        "shrink the left boundary and repeat",
        "return the sorted array",
    ],
    "gnome_sort": [
        "compare the current value with its predecessor",
        "if they are ordered, move one position forward",
        "otherwise swap them and move one position back",
        "repeat until the end of the array",
        "return the sorted array",
    ],
    "comb_sort": [
        "shrink the comparison gap",
        "compare each pair separated by the gap",
        "swap pairs that are out of order",
        "repeat until the gap is one and no swaps occur",
        "return the sorted array",
    ],
    "counting_sort": [
        "find the minimum and maximum values",
        "count how often each value occurs",
        "iterate through the counts in ascending order",
        "write each value back for its recorded count",
        "return the sorted array",
    ],
    "linear_search": [
        "for each value from left to right",
        "  compare the value with the target",
        "  if they match, report its index",
        "report that the target was not found",
        "finish the search",
    ],
    "binary_search": [
        "set low and high around the candidate range",
        "while low is not beyond high",
        "  inspect the midpoint value",
        "  if it matches, report its index",
        "  if it is smaller, search the right half",
        "  otherwise search the left half",
        "report that the target was not found",
        "finish the search",
    ],
    "bst_insert": [
        "start with an empty binary search tree",
        "if the tree is empty, insert the value as root",
        "compare the value with the current node",
        "move left for smaller values, otherwise move right",
        "insert the value at the first empty child",
        "finish with the completed tree",
    ],
    "bst_search": [
        "start at the root node",
        "compare the target with the current node",
        "if the target is smaller, move left",
        "if the target matches, report success",
        "if the target is larger, move right",
        "repeat until a node or empty child is reached",
        "report that the target was not found",
        "finish the search",
    ],
    "inorder_traversal": [
        "start at the root node",
        "traverse the left subtree",
        "visit the current node",
        "traverse the right subtree",
        "repeat recursively for every node",
        "finish with the visited order",
    ],
    "preorder_traversal": [
        "start at the root node",
        "visit the current node",
        "traverse the left subtree",
        "traverse the right subtree",
        "repeat recursively for every node",
        "finish with the visited order",
    ],
    "postorder_traversal": [
        "start at the root node",
        "traverse the left subtree",
        "traverse the right subtree",
        "visit the current node",
        "repeat recursively for every node",
        "finish with the visited order",
    ],
    "fibonacci": [
        "create a table for Fibonacci values from 0 through n",
        "set F(0) to 0 and F(1) to 1 when needed",
        "for each index from 2 through n",
        "  store F(i) as F(i - 1) plus F(i - 2)",
        "return F(n)",
    ],
    "coin_change": [
        "create a table for coin prefixes and target amounts",
        "set amount 0 to 0 coins and other amounts to infinity",
        "for each coin row",
        "  for each amount",
        "    compare skipping the coin with using the coin again",
        "    choose the smaller coin count",
        "return the final count or report not possible",
    ],
    "knapsack": [
        "create a table for item prefixes and capacities",
        "for each item",
        "  for each capacity",
        "    compare the best value without and with the item",
        "    choose the item when it improves the value",
        "    otherwise carry forward the previous best",
        "return the best value in the final cell",
    ],
    "lcs": [
        "create a table for prefixes of both strings",
        "for each character in the first string",
        "  for each character in the second string",
        "    if the characters match, extend the diagonal subsequence",
        "    otherwise choose the longer top or left prefix",
        "backtrack through the table to build a subsequence",
        "return the subsequence",
    ],
    "edit_distance": [
        "create a table for source and target prefixes",
        "initialize empty-string row and column costs",
        "for each source character",
        "  for each target character",
        "    if characters match, copy the diagonal cost",
        "    otherwise choose insert, delete, or replace plus one",
        "return the final edit distance",
    ],
    "unique_paths": [
        "create a grid for path counts",
        "set the first row and first column to 1",
        "for each inner row",
        "  for each inner column",
        "    add paths from the cell above and the cell to the left",
        "return the bottom-right count",
    ],
    "n_queens": [
        "start with an empty chess board",
        "for each row, try every column",
        "  mark the candidate square",
        "  if no queen attacks it, place a queen",
        "  recursively solve the next row",
        "  remove the queen when the branch fails",
        "report the first complete placement",
    ],
    "maze_solver": [
        "start at the maze entrance",
        "mark the current cell as visited",
        "move into the current cell",
        "if this cell is the exit, report the path",
        "try each neighboring cell",
        "skip walls, boundaries, and visited cells",
        "backtrack when no neighbor can continue",
        "finish when a route is found or all branches fail",
    ],
    "permutations": [
        "start with an empty permutation",
        "if the permutation contains every value, record it",
        "for each input value",
        "  skip values already used in this branch",
        "  choose the value and recurse",
        "  return from recursion",
        "  unchoose the value",
        "finish after all choices have been explored",
    ],
    "subsets": [
        "start with an empty subset",
        "if every value has been considered, record the subset",
        "otherwise inspect the next value",
        "decide whether to include it",
        "include the value and recurse",
        "unchoose the value",
        "exclude the value and recurse",
        "finish after all include/exclude branches",
    ],
    "sudoku_solver": [
        "start with the Sudoku puzzle",
        "find the next empty cell",
        "try each digit from 1 through 9",
        "check whether the digit is safe",
        "place the digit and recurse",
        "remove the digit when the branch fails",
        "report the solution when no empty cells remain",
        "finish the search",
    ],
    "bfs": [
        "enqueue the start node",
        "dequeue the next node",
        "mark the node as visited",
        "if it is the target, reconstruct the path",
        "inspect each outgoing edge",
        "enqueue each undiscovered neighbor",
        "report whether a path was found",
        "finish the search",
    ],
    "dfs": [
        "push the start node onto the stack",
        "pop the next node",
        "mark the node as visited",
        "if it is the target, reconstruct the path",
        "inspect each outgoing edge",
        "push each undiscovered neighbor",
        "report whether a path was found",
        "finish the search",
    ],
    "dijkstra": [
        "add the start node with distance zero",
        "remove the node with the smallest distance",
        "mark the node as visited",
        "if it is the target, reconstruct the path",
        "inspect each outgoing edge",
        "relax the edge when it gives a shorter distance",
        "report whether a shortest path was found",
        "finish the search",
    ],
    "a_star": [
        "add the start node with its estimated cost",
        "remove the node with the smallest estimated cost",
        "move the node to the closed set",
        "if it is the target, reconstruct the path",
        "inspect each outgoing edge",
        "update a neighbor when its new path is better",
        "report whether a shortest path was found",
        "finish the search",
    ],
    "topological_sort": [
        "collect all nodes with zero in-degree",
        "remove a zero in-degree node",
        "add the node to the result",
        "decrease each outgoing neighbor's in-degree",
        "add newly available neighbors to the frontier",
        "report a cycle if not every node was processed",
        "finish with the topological order",
    ],
    "kruskal": [
        "sort all edges by increasing weight",
        "inspect the next lightest edge",
        "accept it if it joins two components",
        "otherwise reject it to avoid a cycle",
        "repeat for every edge",
        "return the minimum spanning forest",
    ],
    "prim": [
        "start a component and add its candidate edges",
        "remove the lightest candidate edge",
        "reject it if its target is already visited",
        "otherwise accept it into the forest",
        "visit the new node and add its candidate edges",
        "repeat for disconnected components",
        "return the minimum spanning forest",
    ],
}


SORTING_ALGORITHM_METADATA = [
    metadata(
        "bubble_sort",
        "Bubble Sort",
        "sorting",
        "Repeatedly compares neighboring values and swaps pairs that are out of order.",
        "O(n)",
        "O(n²)",
        "O(n²)",
        "O(1)",
        "Stable and in-place.",
        "The early-exit check makes already sorted input linear.",
    ),
    metadata(
        "selection_sort",
        "Selection Sort",
        "sorting",
        "Selects the smallest remaining value and places it at the next sorted position.",
        "O(n²)",
        "O(n²)",
        "O(n²)",
        "O(1)",
        "In-place but not stable in its usual form.",
        "Performs few swaps, but always scans the unsorted suffix.",
    ),
    metadata(
        "insertion_sort",
        "Insertion Sort",
        "sorting",
        "Builds a sorted prefix by inserting each new value into its correct position.",
        "O(n)",
        "O(n²)",
        "O(n²)",
        "O(1)",
        "Stable and in-place.",
        "Works well for small or nearly sorted inputs.",
    ),
    metadata(
        "merge_sort",
        "Merge Sort",
        "sorting",
        "Recursively divides the array and merges sorted sections back together.",
        "O(n log n)",
        "O(n log n)",
        "O(n log n)",
        "O(n)",
        "Stable in this implementation.",
        "Requires auxiliary arrays while merging.",
    ),
    metadata(
        "quick_sort",
        "Quick Sort",
        "sorting",
        "Partitions values around a pivot, then recursively sorts both partitions.",
        "O(n log n)",
        "O(n log n)",
        "O(n²)",
        "O(log n) average, O(n) worst",
        "In-place apart from recursion, but not stable.",
        "Uses the final element as pivot, so ordered inputs can produce the worst case.",
    ),
    metadata(
        "heap_sort",
        "Heap Sort",
        "sorting",
        "Builds a max heap and repeatedly moves its largest value to the array's end.",
        "O(n log n)",
        "O(n log n)",
        "O(n log n)",
        "O(log n)",
        "In-place apart from recursive heapify calls.",
        "Not stable.",
    ),
    metadata(
        "shell_sort",
        "Shell Sort",
        "sorting",
        "Runs insertion-style passes over shrinking gaps before a final adjacent pass.",
        "O(n log n)",
        "O(n²)",
        "O(n²)",
        "O(1)",
        "In-place and not stable.",
        "Bounds depend on the gap sequence; this implementation repeatedly halves the gap.",
    ),
    metadata(
        "cocktail_shaker_sort",
        "Cocktail Shaker Sort",
        "sorting",
        "Alternates forward and backward bubble passes to move extremes in both directions.",
        "O(n)",
        "O(n²)",
        "O(n²)",
        "O(1)",
        "Stable and in-place.",
        "Still quadratic for typical and adverse inputs.",
    ),
    metadata(
        "gnome_sort",
        "Gnome Sort",
        "sorting",
        "Walks forward through ordered pairs and steps backward whenever it swaps a pair.",
        "O(n)",
        "O(n²)",
        "O(n²)",
        "O(1)",
        "Stable and in-place.",
        "Simple, but inefficient for large unsorted arrays.",
    ),
    metadata(
        "comb_sort",
        "Comb Sort",
        "sorting",
        "Compares values across a shrinking gap to remove small values near the array's end.",
        "O(n log n)",
        "O(n²)",
        "O(n²)",
        "O(1)",
        "In-place and not stable.",
        "Performance depends on the shrink factor and input distribution.",
    ),
    metadata(
        "counting_sort",
        "Counting Sort",
        "sorting",
        "Counts each integer value and writes values back in ascending order.",
        "O(n + k)",
        "O(n + k)",
        "O(n + k)",
        "O(k)",
        "Here k is the range between the minimum and maximum values.",
        "Supports negative integers, but a very wide value range uses substantial memory.",
    ),
]


SEARCHING_ALGORITHM_METADATA = [
    metadata(
        "linear_search",
        "Linear Search",
        "searching",
        "Checks values from left to right until the target is found or input is exhausted.",
        "O(1)",
        "O(n)",
        "O(n)",
        "O(1)",
        "Works with unsorted input.",
        "Returns the first matching position encountered.",
    ),
    metadata(
        "binary_search",
        "Binary Search",
        "searching",
        "Repeatedly halves the candidate interval by comparing its midpoint with the target.",
        "O(1)",
        "O(log n)",
        "O(log n)",
        "O(1)",
        "Requires values sorted in ascending order.",
        "With duplicates, the returned match is not guaranteed to be the first occurrence.",
    ),
]


TREES_ALGORITHM_METADATA = [
    metadata(
        "bst_insert",
        "BST Insert",
        "trees",
        "Builds a binary search tree by inserting each value according to BST ordering.",
        "O(log n)",
        "O(log n)",
        "O(n)",
        "O(n)",
        "Input values must be unique in this version.",
        "Tree shape depends on insertion order; sorted input can create a tall tree.",
    ),
    metadata(
        "bst_search",
        "BST Search",
        "trees",
        "Searches a binary search tree by moving left or right after each comparison.",
        "O(1)",
        "O(log n)",
        "O(n)",
        "O(1)",
        "Search performance depends on how balanced the tree is.",
        "This is a tree search, not the existing array Binary Search algorithm.",
    ),
    metadata(
        "inorder_traversal",
        "Inorder Traversal",
        "trees",
        "Visits a binary search tree in left-node-right order.",
        "O(n)",
        "O(n)",
        "O(n)",
        "O(h)",
        "For a BST, inorder traversal returns values in sorted order.",
        "Here h is the tree height from recursive traversal.",
    ),
    metadata(
        "preorder_traversal",
        "Preorder Traversal",
        "trees",
        "Visits a binary tree in node-left-right order.",
        "O(n)",
        "O(n)",
        "O(n)",
        "O(h)",
        "Useful for recording a tree before its children.",
        "Here h is the tree height from recursive traversal.",
    ),
    metadata(
        "postorder_traversal",
        "Postorder Traversal",
        "trees",
        "Visits a binary tree in left-right-node order.",
        "O(n)",
        "O(n)",
        "O(n)",
        "O(h)",
        "Useful when children must be processed before their parent.",
        "Here h is the tree height from recursive traversal.",
    ),
]


GRAPH_ALGORITHM_METADATA = [
    metadata(
        "bfs",
        "Breadth-First Search",
        "graph",
        "Explores nodes level by level with a queue and finds a minimum-edge path.",
        "O(V + E)",
        "O(V + E)",
        "O(V + E)",
        "O(V + E)",
        "Finds shortest paths by edge count, not by total edge weight.",
        "Supports directed and undirected graphs.",
    ),
    metadata(
        "dfs",
        "Depth-First Search",
        "graph",
        "Explores one branch deeply before backtracking to another branch.",
        "O(V + E)",
        "O(V + E)",
        "O(V + E)",
        "O(V + E)",
        "Does not guarantee a shortest path.",
        "Supports directed and undirected graphs.",
    ),
    metadata(
        "dijkstra",
        "Dijkstra's Algorithm",
        "graph",
        "Uses a priority queue to find a minimum-cost path from the start node.",
        "O((V + E) log V)",
        "O((V + E) log V)",
        "O((V + E) log V)",
        "O(V + E)",
        "Requires non-negative edge weights.",
        "Supports directed and undirected graphs.",
    ),
    metadata(
        "a_star",
        "A* Search",
        "graph",
        "Prioritizes nodes using path cost plus a heuristic estimate to the target.",
        "O(E)",
        "O(E log V)",
        "O(E log V)",
        "O(V + E)",
        "Requires non-negative edge weights.",
        "Optimality requires an admissible heuristic; a zero heuristic behaves like Dijkstra's algorithm.",
    ),
    metadata(
        "topological_sort",
        "Topological Sort",
        "graph",
        "Uses Kahn's algorithm to order nodes after all of their prerequisites.",
        "O(V + E)",
        "O(V + E)",
        "O(V + E)",
        "O(V + E)",
        "Requires a directed acyclic graph for a complete ordering.",
        "Reports a cycle when no complete topological order exists.",
    ),
    metadata(
        "kruskal",
        "Kruskal's Minimum Spanning Tree",
        "graph",
        "Adds edges in increasing weight order while avoiding cycles with disjoint sets.",
        "O(E log E)",
        "O(E log E)",
        "O(E log E)",
        "O(V + E)",
        "Treats edges as undirected.",
        "Returns a minimum spanning forest when the graph is disconnected.",
    ),
    metadata(
        "prim",
        "Prim's Minimum Spanning Tree",
        "graph",
        "Grows a spanning tree by repeatedly accepting the lightest edge to a new node.",
        "O(E log V)",
        "O(E log V)",
        "O(E log V)",
        "O(V + E)",
        "Treats edges as undirected and uses the selected start node first.",
        "Returns a minimum spanning forest when the graph is disconnected.",
    ),
]


DYNAMIC_PROGRAMMING_ALGORITHM_METADATA = [
    metadata(
        "fibonacci",
        "Fibonacci DP",
        "dynamic_programming",
        "Builds Fibonacci numbers from smaller saved subproblems.",
        "O(n)",
        "O(n)",
        "O(n)",
        "O(n)",
        "Demonstrates one-dimensional tabulation.",
        "The table keeps every value so the visualization can show the recurrence.",
    ),
    metadata(
        "coin_change",
        "Coin Change",
        "dynamic_programming",
        "Finds the minimum number of unlimited coins needed for a target amount.",
        "O(ca)",
        "O(ca)",
        "O(ca)",
        "O(ca)",
        "Here c is the number of coin types and a is the target amount.",
        "Impossible amounts are displayed as infinity and reported as not possible.",
    ),
    metadata(
        "knapsack",
        "0/1 Knapsack",
        "dynamic_programming",
        "Chooses items to maximize value without exceeding a capacity limit.",
        "O(nW)",
        "O(nW)",
        "O(nW)",
        "O(nW)",
        "Each item can be chosen at most once.",
        "Here n is item count and W is the capacity.",
    ),
    metadata(
        "lcs",
        "Longest Common Subsequence",
        "dynamic_programming",
        "Finds a longest sequence that appears in both strings in order.",
        "O(mn)",
        "O(mn)",
        "O(mn)",
        "O(mn)",
        "Subsequence characters do not need to be adjacent.",
        "When several answers are valid, this implementation uses deterministic tie-breaking.",
    ),
    metadata(
        "edit_distance",
        "Edit Distance",
        "dynamic_programming",
        "Computes the fewest inserts, deletes, and replacements between two strings.",
        "O(mn)",
        "O(mn)",
        "O(mn)",
        "O(mn)",
        "Also known as Levenshtein distance.",
        "Every table cell represents the cost for a pair of string prefixes.",
    ),
    metadata(
        "unique_paths",
        "Grid Unique Paths",
        "dynamic_programming",
        "Counts paths across a grid when movement is limited to right and down.",
        "O(rc)",
        "O(rc)",
        "O(rc)",
        "O(rc)",
        "Here r is row count and c is column count.",
        "The first row and column each have exactly one route.",
    ),
]


BACKTRACKING_ALGORITHM_METADATA = [
    metadata(
        "n_queens",
        "N-Queens",
        "backtracking",
        "Places queens one row at a time so no two queens attack each other.",
        "O(n!)",
        "O(n!)",
        "O(n!)",
        "O(n)",
        "Stops after the first valid placement.",
        "Shows attempted squares, conflicts, placements, removals, and the final solution.",
    ),
    metadata(
        "maze_solver",
        "Maze Solver",
        "backtracking",
        "Uses depth-first search with backtracking to find a path through a maze.",
        "O(rc)",
        "O(rc)",
        "O(rc)",
        "O(rc)",
        "Here r is row count and c is column count.",
        "Uses deterministic generated maze presets for repeatable visualizations.",
    ),
    metadata(
        "permutations",
        "Permutations",
        "backtracking",
        "Builds every ordering of a list by choosing each unused value in turn.",
        "O(n · n!)",
        "O(n · n!)",
        "O(n · n!)",
        "O(n)",
        "Input is limited to 6 values to keep the step stream readable.",
        "Duplicate input values are treated as distinct positions.",
    ),
    metadata(
        "subsets",
        "Subsets",
        "backtracking",
        "Builds the power set by making an include or exclude decision for each value.",
        "O(n · 2ⁿ)",
        "O(n · 2ⁿ)",
        "O(n · 2ⁿ)",
        "O(n)",
        "Input is limited to 10 values to keep output size bounded.",
        "The empty subset is included in the generated results.",
    ),
    metadata(
        "sudoku_solver",
        "Sudoku Solver",
        "backtracking",
        "Fills a 9 by 9 Sudoku board by trying safe digits and backtracking from contradictions.",
        "O(1)",
        "O(9ᵉ)",
        "O(9ᵉ)",
        "O(e)",
        "Here e is the number of empty cells in the puzzle.",
        "Accepts empty cells as 0 or '.'.",
    ),
]


ALGORITHM_METADATA = [
    *SORTING_ALGORITHM_METADATA,
    *SEARCHING_ALGORITHM_METADATA,
    *TREES_ALGORITHM_METADATA,
    *GRAPH_ALGORITHM_METADATA,
    *DYNAMIC_PROGRAMMING_ALGORITHM_METADATA,
    *BACKTRACKING_ALGORITHM_METADATA,
]
